# Generated by Django 5.1.2 on 2024-11-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_subcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcategory',
            table='SubCategory',
        ),
    ]
