# Generated by Django 5.1.2 on 2024-11-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_subcategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subcategory')),
            ],
            options={
                'db_table': 'SubClass',
            },
        ),
    ]
