# Generated by Django 5.1.2 on 2024-11-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_video'),
        ('catalog', '0006_product_discount_product_quantity'),
    ]

    operations = [
    ]
